#!/usr/bin/perl

use strict;
use warnings;

my $timeout = 5; # secs

my $target = shift or die "usage: ricocheck TARGET\nExample: ricocheck it2j3z6t6ksumpzd\nThere's a bit of DWIM, in that \"ricochet:\" and \".onion\" are automatically stripped from the TARGET.\n";

$target = lc $target;
$target =~ s/\.onion$//;
$target =~ s/^ricochet://;

$SIG{ALRM} = sub { print "timeout\n"; exit 1; };

alarm($timeout);

my $rc = system("torsocks", "nc", "-w", $timeout, "-z", "$target.onion", "9878");
print "online\n" if $rc == 0;
print "offline\n" if $rc != 0;
